name: dart_odbc
description: ODBC api for dart .
version: 1.0.0
repository: https://github.com/SL-Pirate/dart-odbc

environment:
  sdk: '>=3.0.0 <=3.3.4'

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0

topics:
  - db
  - database
  - odbc
  - sqlserver
  - oracle
