name: dart_odbc
description: A Dart package for interacting with ODBC databases. It allows you to connect to ODBC data sources and execute SQL queries directly from your Dart applications.
version: 1.0.2+1
repository: https://github.com/SL-Pirate/dart_odbc

environment:
  sdk: '>=3.0.0 <=3.3.4'

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0

topics:
  - db
  - database
  - odbc
  - sqlserver
  - oracle
